// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_DvxtpQLQNChFgyp4BPOSTaak308qnV8',
    appId: '1:1036381825912:web:8a58c292f1024c3139b68d',
    messagingSenderId: '1036381825912',
    projectId: 'coffeeshop-95771',
    authDomain: 'coffeeshop-95771.firebaseapp.com',
    storageBucket: 'coffeeshop-95771.appspot.com',
    measurementId: 'G-EBDCV5RYEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Z9n98A6_BmzMmDFk_jyfAQ-WxL5iVyU',
    appId: '1:1036381825912:android:c8656d10dd3a25cc39b68d',
    messagingSenderId: '1036381825912',
    projectId: 'coffeeshop-95771',
    storageBucket: 'coffeeshop-95771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSS9K7xBrP8I2HnkHsJOVPrcu81awLoTI',
    appId: '1:1036381825912:ios:31b7e214e07491fc39b68d',
    messagingSenderId: '1036381825912',
    projectId: 'coffeeshop-95771',
    storageBucket: 'coffeeshop-95771.appspot.com',
    iosClientId: '1036381825912-eams4g1ri3ctqlvqpigmoivm2jfeib03.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSS9K7xBrP8I2HnkHsJOVPrcu81awLoTI',
    appId: '1:1036381825912:ios:0e7b1082f420bf4439b68d',
    messagingSenderId: '1036381825912',
    projectId: 'coffeeshop-95771',
    storageBucket: 'coffeeshop-95771.appspot.com',
    iosClientId: '1036381825912-op0evselnumvkotoecjodn17e5olif35.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeApp.RunnerTests',
  );
}
